version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/crypto_api
    command: python crypto_api/manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=TRUE
